version: "2"

services: 
  
  server:
    build: "./"
    ports: 
      - "8080:80"
    command: "server"

  drone:
    build: "./"
    environment:
      MASTER_HOST: http://server
    command: "drone"
